<a href="https://colab.research.google.com/github/jarekStrzelecki/data-science-bootcamp/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Algebra liniowa")

Algebra liniowa


In [1]:
import numpy as np

In [3]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1],[-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [4]:
Z = np.dot(X,Y)
print(Z)

[[ 2]
 [-6]]


In [5]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [6]:
A = np.array([[2,4], [-1, 3]])
np.trace(A)

5

In [3]:
import numpy as np
A = np.eye(2, dtype='int')
print(A)

[[1 0]
 [0 1]]


In [5]:
A = np.array([[2,4], [-1,3]])
B = np.linalg.inv(A)
print(B)

[[ 0.3 -0.4]
 [ 0.1  0.2]]


In [6]:
A = np.array([[2,4], [-1,3]])
print(np.transpose(A))

[[ 2 -1]
 [ 4  3]]


In [7]:
print(A.T)

[[ 2 -1]
 [ 4  3]]


In [8]:
A = np.array([[2,4], [1,-1]])
B = np.array([[10],[-1]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]


In [9]:
price = np.array([ [12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [10]:
X = np.array([2., -3, 4])
print(X.dtype)


float64
