<a href="https://colab.research.google.com/github/jarekStrzelecki/data-science-bootcamp/blob/main/wprowadzenie/wprowadzenie_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print('Hello')

Hello


In [2]:
import numpy as np


In [6]:
A = np.array([1,2,3], dtype='float')
print(A)

[1. 2. 3.]


In [8]:
z = np.zeros(shape=(4,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [3]:
X = np.array([ [1,3], [-2,0]])
Y = np.array([ [6,0], [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [4]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [5]:
np.random.randn()

-0.675700646537951

In [7]:
A = np.random.rand(5)
A

array([0.57224322, 0.89088471, 0.40320559, 0.80400446, 0.02084789])

In [10]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
A = A.reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
A[2]

array([10, 11, 12, 13, 14])

In [17]:
A[:,-1]

array([ 4,  9, 14, 19])

In [18]:
A[1,1]

6

In [21]:
A[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])